services:
  backend:
    build: .
    command: node dist/main.js
    env_file: ./.env
    ports:
      - '3334:3001'
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=indulasch
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
    command: --quiet
    ports:
      - '3335:27017'
    volumes:
      - ./database_volume:/data/db
volumes:
  database_volume: